import pyglet
from pyglet.image import Animation

pyglet.resource.path = ["/home/clayton/Pictures/sprites/platformer"]
pyglet.resource.reindex()

class EnemyImages:
    blockerBody = pyglet.resource.image("Enemies/blockerBody.png")
    blockerMad = pyglet.resource.image("Enemies/blockerMad.png")
    blockerSad = pyglet.resource.image("Enemies/blockerSad.png")
    enemies_spritesheet = pyglet.resource.image("Enemies/enemies_spritesheet.png")
    fishDead = pyglet.resource.image("Enemies/fishDead.png")
    fishSwim1 = pyglet.resource.image("Enemies/fishSwim1.png")
    fishSwim2 = pyglet.resource.image("Enemies/fishSwim2.png")
    flyDead = pyglet.resource.image("Enemies/flyDead.png")
    flyFly1 = pyglet.resource.image("Enemies/flyFly1.png")
    flyFly2 = pyglet.resource.image("Enemies/flyFly2.png")
    pokerMad = pyglet.resource.image("Enemies/pokerMad.png")
    pokerSad = pyglet.resource.image("Enemies/pokerSad.png")
    slimeDead = pyglet.resource.image("Enemies/slimeDead.png")
    slimeWalk1 = pyglet.resource.image("Enemies/slimeWalk1.png")
    slimeWalk2 = pyglet.resource.image("Enemies/slimeWalk2.png")
    snailShell = pyglet.resource.image("Enemies/snailShell.png")
    snailShell_upsidedown = pyglet.resource.image("Enemies/snailShell_upsidedown.png")
    snailWalk1 = pyglet.resource.image("Enemies/snailWalk1.png")
    snailWalk2 = pyglet.resource.image("Enemies/snailWalk2.png")

class HUDImages:
    hud_0 = pyglet.resource.image("HUD/hud_0.png")
    hud_1 = pyglet.resource.image("HUD/hud_1.png")
    hud_2 = pyglet.resource.image("HUD/hud_2.png")
    hud_3 = pyglet.resource.image("HUD/hud_3.png")
    hud_4 = pyglet.resource.image("HUD/hud_4.png")
    hud_5 = pyglet.resource.image("HUD/hud_5.png")
    hud_6 = pyglet.resource.image("HUD/hud_6.png")
    hud_7 = pyglet.resource.image("HUD/hud_7.png")
    hud_8 = pyglet.resource.image("HUD/hud_8.png")
    hud_9 = pyglet.resource.image("HUD/hud_9.png")
    hud_coins = pyglet.resource.image("HUD/hud_coins.png")
    hud_gem_blue = pyglet.resource.image("HUD/hud_gem_blue.png")
    hud_gem_green = pyglet.resource.image("HUD/hud_gem_green.png")
    hud_gem_red = pyglet.resource.image("HUD/hud_gem_red.png")
    hud_gem_yellow = pyglet.resource.image("HUD/hud_gem_yellow.png")
    hud_heartEmpty = pyglet.resource.image("HUD/hud_heartEmpty.png")
    hud_heartFull = pyglet.resource.image("HUD/hud_heartFull.png")
    hud_heartHalf = pyglet.resource.image("HUD/hud_heartHalf.png")
    hud_keyBlue_disabled = pyglet.resource.image("HUD/hud_keyBlue_disabled.png")
    hud_keyBlue = pyglet.resource.image("HUD/hud_keyBlue.png")
    hud_keyGreem_disabled = pyglet.resource.image("HUD/hud_keyGreem_disabled.png")
    hud_keyGreen = pyglet.resource.image("HUD/hud_keyGreen.png")
    hud_keyRed_disabled = pyglet.resource.image("HUD/hud_keyRed_disabled.png")
    hud_keyRed = pyglet.resource.image("HUD/hud_keyRed.png")
    hud_keyYellow_disabled = pyglet.resource.image("HUD/hud_keyYellow_disabled.png")
    hud_keyYellow = pyglet.resource.image("HUD/hud_keyYellow.png")
    hud_p1Alt = pyglet.resource.image("HUD/hud_p1Alt.png")
    hud_p1 = pyglet.resource.image("HUD/hud_p1.png")
    hud_p2Alt = pyglet.resource.image("HUD/hud_p2Alt.png")
    hud_p2 = pyglet.resource.image("HUD/hud_p2.png")
    hud_p3Alt = pyglet.resource.image("HUD/hud_p3Alt.png")
    hud_p3 = pyglet.resource.image("HUD/hud_p3.png")
    hud_spritesheet = pyglet.resource.image("HUD/hud_spritesheet.png")
    hud_x = pyglet.resource.image("HUD/hud_x.png")

class ItemImages:
    bombFlash = pyglet.resource.image("Items/bombFlash.png")
    bomb = pyglet.resource.image("Items/bomb.png")
    bush = pyglet.resource.image("Items/bush.png")
    buttonBlue = pyglet.resource.image("Items/buttonBlue.png")
    buttonBlue_pressed = pyglet.resource.image("Items/buttonBlue_pressed.png")
    buttonGreen = pyglet.resource.image("Items/buttonGreen.png")
    buttonGreen_pressed = pyglet.resource.image("Items/buttonGreen_pressed.png")
    buttonRed = pyglet.resource.image("Items/buttonRed.png")
    buttonRed_pressed = pyglet.resource.image("Items/buttonRed_pressed.png")
    buttonYellow = pyglet.resource.image("Items/buttonYellow.png")
    buttonYellow_pressed = pyglet.resource.image("Items/buttonYellow_pressed.png")
    cactus = pyglet.resource.image("Items/cactus.png")
    chain = pyglet.resource.image("Items/chain.png")
    cloud1 = pyglet.resource.image("Items/cloud1.png")
    cloud2 = pyglet.resource.image("Items/cloud2.png")
    cloud3 = pyglet.resource.image("Items/cloud3.png")
    coinBronze = pyglet.resource.image("Items/coinBronze.png")
    coinGold = pyglet.resource.image("Items/coinGold.png")
    coinSilver = pyglet.resource.image("Items/coinSilver.png")
    fireball = pyglet.resource.image("Items/fireball.png")
    flagBlue2 = pyglet.resource.image("Items/flagBlue2.png")
    flagBlueHanging = pyglet.resource.image("Items/flagBlueHanging.png")
    flagBlue = pyglet.resource.image("Items/flagBlue.png")
    flagGreen2 = pyglet.resource.image("Items/flagGreen2.png")
    flagGreenHanging = pyglet.resource.image("Items/flagGreenHanging.png")
    flagGreen = pyglet.resource.image("Items/flagGreen.png")
    flagRed2 = pyglet.resource.image("Items/flagRed2.png")
    flagRedHanging = pyglet.resource.image("Items/flagRedHanging.png")
    flagRed = pyglet.resource.image("Items/flagRed.png")
    flagYellow2 = pyglet.resource.image("Items/flagYellow2.png")
    flagYellowHanging = pyglet.resource.image("Items/flagYellowHanging.png")
    flagYellow = pyglet.resource.image("Items/flagYellow.png")
    gemBlue = pyglet.resource.image("Items/gemBlue.png")
    gemGreen = pyglet.resource.image("Items/gemGreen.png")
    gemRed = pyglet.resource.image("Items/gemRed.png")
    gemYellow = pyglet.resource.image("Items/gemYellow.png")
    items_spritesheet = pyglet.resource.image("Items/items_spritesheet.png")
    keyBlue = pyglet.resource.image("Items/keyBlue.png")
    keyGreen = pyglet.resource.image("Items/keyGreen.png")
    keyRed = pyglet.resource.image("Items/keyRed.png")
    keyYellow = pyglet.resource.image("Items/keyYellow.png")
    mushroomBrown = pyglet.resource.image("Items/mushroomBrown.png")
    mushroomRed = pyglet.resource.image("Items/mushroomRed.png")
    particleBrick1a = pyglet.resource.image("Items/particleBrick1a.png")
    particleBrick1b = pyglet.resource.image("Items/particleBrick1b.png")
    particleBrick2a = pyglet.resource.image("Items/particleBrick2a.png")
    particleBrick2b = pyglet.resource.image("Items/particleBrick2b.png")
    plant = pyglet.resource.image("Items/plant.png")
    plantPurple = pyglet.resource.image("Items/plantPurple.png")
    rock = pyglet.resource.image("Items/rock.png")
    snowhill = pyglet.resource.image("Items/snowhill.png")
    spikes = pyglet.resource.image("Items/spikes.png")
    springboardDown = pyglet.resource.image("Items/springboardDown.png")
    springboardUp = pyglet.resource.image("Items/springboardUp.png")
    star = pyglet.resource.image("Items/star.png")
    switchLeft = pyglet.resource.image("Items/switchLeft.png")
    switchMid = pyglet.resource.image("Items/switchMid.png")
    switchRight = pyglet.resource.image("Items/switchRight.png")
    weightChained = pyglet.resource.image("Items/weightChained.png")
    weight = pyglet.resource.image("Items/weight.png")

class PlayerImages:
    class p1:
        duck = pyglet.resource.image("Player/p1_duck.png")
        front = pyglet.resource.image("Player/p1_front.png")
        hurt = pyglet.resource.image("Player/p1_hurt.png")
        jump = pyglet.resource.image("Player/p1_jump.png")
        spritesheet = pyglet.resource.image("Player/p1_spritesheet.png")
        stand = pyglet.resource.image("Player/p1_stand.png")
        walk = pyglet.resource.image("Player/p1_walk/p1_walk.png")
        walk01 = pyglet.resource.image("Player/p1_walk/PNG/p1_walk01.png")
        walk02 = pyglet.resource.image("Player/p1_walk/PNG/p1_walk02.png")
        walk03 = pyglet.resource.image("Player/p1_walk/PNG/p1_walk03.png")
        walk04 = pyglet.resource.image("Player/p1_walk/PNG/p1_walk04.png")
        walk05 = pyglet.resource.image("Player/p1_walk/PNG/p1_walk05.png")
        walk06 = pyglet.resource.image("Player/p1_walk/PNG/p1_walk06.png")
        walk07 = pyglet.resource.image("Player/p1_walk/PNG/p1_walk07.png")
        walk08 = pyglet.resource.image("Player/p1_walk/PNG/p1_walk08.png")
        walk09 = pyglet.resource.image("Player/p1_walk/PNG/p1_walk09.png")
        walk10 = pyglet.resource.image("Player/p1_walk/PNG/p1_walk10.png")
        walk11 = pyglet.resource.image("Player/p1_walk/PNG/p1_walk11.png")
        walk_seq = [
            walk01, walk02, walk03, walk04, walk05, walk06, walk07,
            walk08, walk09, walk10, walk11
        ]

        # Need to change anchor position to center so that the player doesn't move when flipped
        for img in walk_seq + [stand]:
            img.anchor_x = img.width // 2
        walk_right_seq = [img.get_transform(flip_x=False) for img in walk_seq]
        walk_left_seq = [img.get_transform(flip_x=True) for img in walk_seq]
        idle_right = stand.get_transform(flip_x=False)
        idle_left = stand.get_transform(flip_x=True)

        walk_right_anim = Animation.from_image_sequence(sequence=walk_right_seq, duration=1/20, loop=True)
        walk_left_anim = Animation.from_image_sequence(sequence=walk_left_seq, duration=1/20, loop=True)

    class p2:
        duck = pyglet.resource.image("Player/p2_duck.png")
        front = pyglet.resource.image("Player/p2_front.png")
        hurt = pyglet.resource.image("Player/p2_hurt.png")
        jump = pyglet.resource.image("Player/p2_jump.png")
        spritesheet = pyglet.resource.image("Player/p2_spritesheet.png")
        stand = pyglet.resource.image("Player/p2_stand.png")
        walk = pyglet.resource.image("Player/p2_walk/p2_walk.png")
        walk01 = pyglet.resource.image("Player/p2_walk/PNG/p2_walk01.png")
        walk02 = pyglet.resource.image("Player/p2_walk/PNG/p2_walk02.png")
        walk03 = pyglet.resource.image("Player/p2_walk/PNG/p2_walk03.png")
        walk04 = pyglet.resource.image("Player/p2_walk/PNG/p2_walk04.png")
        walk05 = pyglet.resource.image("Player/p2_walk/PNG/p2_walk05.png")
        walk06 = pyglet.resource.image("Player/p2_walk/PNG/p2_walk06.png")
        walk07 = pyglet.resource.image("Player/p2_walk/PNG/p2_walk07.png")
        walk08 = pyglet.resource.image("Player/p2_walk/PNG/p2_walk08.png")
        walk09 = pyglet.resource.image("Player/p2_walk/PNG/p2_walk09.png")
        walk10 = pyglet.resource.image("Player/p2_walk/PNG/p2_walk10.png")
        walk11 = pyglet.resource.image("Player/p2_walk/PNG/p2_walk11.png")
        walk_seq = [
            walk01, walk02, walk03, walk04, walk05, walk06, walk07,
            walk08, walk09, walk10, walk11
        ]

        # Need to change anchor position to center so that the player doesn't move when flipped
        for img in walk_seq + [stand]:
            img.anchor_x = img.width // 2
        walk_right_seq = [img.get_transform(flip_x=False) for img in walk_seq]
        walk_left_seq = [img.get_transform(flip_x=True) for img in walk_seq]
        idle_right = stand.get_transform(flip_x=False)
        idle_left = stand.get_transform(flip_x=True)

        walk_right_anim = Animation.from_image_sequence(sequence=walk_right_seq, duration=1/20, loop=True)
        walk_left_anim = Animation.from_image_sequence(sequence=walk_left_seq, duration=1/20, loop=True)

    class p3:
        duck = pyglet.resource.image("Player/p3_duck.png")
        front = pyglet.resource.image("Player/p3_front.png")
        hurt = pyglet.resource.image("Player/p3_hurt.png")
        jump = pyglet.resource.image("Player/p3_jump.png")
        spritesheet = pyglet.resource.image("Player/p3_spritesheet.png")
        stand = pyglet.resource.image("Player/p3_stand.png")
        walk = pyglet.resource.image("Player/p3_walk/p3_walk.png")
        walk01 = pyglet.resource.image("Player/p3_walk/PNG/p3_walk01.png")
        walk02 = pyglet.resource.image("Player/p3_walk/PNG/p3_walk02.png")
        walk03 = pyglet.resource.image("Player/p3_walk/PNG/p3_walk03.png")
        walk04 = pyglet.resource.image("Player/p3_walk/PNG/p3_walk04.png")
        walk05 = pyglet.resource.image("Player/p3_walk/PNG/p3_walk05.png")
        walk06 = pyglet.resource.image("Player/p3_walk/PNG/p3_walk06.png")
        walk07 = pyglet.resource.image("Player/p3_walk/PNG/p3_walk07.png")
        walk08 = pyglet.resource.image("Player/p3_walk/PNG/p3_walk08.png")
        walk09 = pyglet.resource.image("Player/p3_walk/PNG/p3_walk09.png")
        walk10 = pyglet.resource.image("Player/p3_walk/PNG/p3_walk10.png")
        walk11 = pyglet.resource.image("Player/p3_walk/PNG/p3_walk11.png")
        walk_seq = [
            walk01, walk02, walk03, walk04, walk05, walk06, walk07,
            walk08, walk09, walk10, walk11
        ]

        # Need to change anchor position to center so that the player doesn't move when flipped
        for img in walk_seq + [stand]:
            img.anchor_x = img.width // 2
        walk_right_seq = [img.get_transform(flip_x=False) for img in walk_seq]
        walk_left_seq = [img.get_transform(flip_x=True) for img in walk_seq]
        idle_right = stand.get_transform(flip_x=False)
        idle_left = stand.get_transform(flip_x=True)

        walk_right_anim = Animation.from_image_sequence(sequence=walk_right_seq, duration=1/20, loop=True)
        walk_left_anim = Animation.from_image_sequence(sequence=walk_left_seq, duration=1/20, loop=True)

class TileImages:
    boxAlt = pyglet.resource.image("Tiles/boxAlt.png")
    boxCoinAlt_disabled = pyglet.resource.image("Tiles/boxCoinAlt_disabled.png")
    boxCoinAlt = pyglet.resource.image("Tiles/boxCoinAlt.png")
    boxCoin_disabled = pyglet.resource.image("Tiles/boxCoin_disabled.png")
    boxCoin = pyglet.resource.image("Tiles/boxCoin.png")
    boxEmpty = pyglet.resource.image("Tiles/boxEmpty.png")
    boxExplosiveAlt = pyglet.resource.image("Tiles/boxExplosiveAlt.png")
    boxExplosive_disabled = pyglet.resource.image("Tiles/boxExplosive_disabled.png")
    boxExplosive = pyglet.resource.image("Tiles/boxExplosive.png")
    boxItemAlt_disabled = pyglet.resource.image("Tiles/boxItemAlt_disabled.png")
    boxItemAlt = pyglet.resource.image("Tiles/boxItemAlt.png")
    boxItem_disabled = pyglet.resource.image("Tiles/boxItem_disabled.png")
    boxItem = pyglet.resource.image("Tiles/boxItem.png")
    box = pyglet.resource.image("Tiles/box.png")
    boxWarning = pyglet.resource.image("Tiles/boxWarning.png")
    brickWall = pyglet.resource.image("Tiles/brickWall.png")
    bridgeLogs = pyglet.resource.image("Tiles/bridgeLogs.png")
    bridge = pyglet.resource.image("Tiles/bridge.png")
    castleCenter = pyglet.resource.image("Tiles/castleCenter.png")
    castleCenter_rounded = pyglet.resource.image("Tiles/castleCenter_rounded.png")
    castleCliffLeftAlt = pyglet.resource.image("Tiles/castleCliffLeftAlt.png")
    castleCliffLeft = pyglet.resource.image("Tiles/castleCliffLeft.png")
    castleCliffRightAlt = pyglet.resource.image("Tiles/castleCliffRightAlt.png")
    castleCliffRight = pyglet.resource.image("Tiles/castleCliffRight.png")
    castleHalfLeft = pyglet.resource.image("Tiles/castleHalfLeft.png")
    castleHalfMid = pyglet.resource.image("Tiles/castleHalfMid.png")
    castleHalf = pyglet.resource.image("Tiles/castleHalf.png")
    castleHalfRight = pyglet.resource.image("Tiles/castleHalfRight.png")
    castleHillLeft2 = pyglet.resource.image("Tiles/castleHillLeft2.png")
    castleHillLeft = pyglet.resource.image("Tiles/castleHillLeft.png")
    castleHillRight2 = pyglet.resource.image("Tiles/castleHillRight2.png")
    castleHillRight = pyglet.resource.image("Tiles/castleHillRight.png")
    castleLedgeLeft = pyglet.resource.image("Tiles/castleLedgeLeft.png")
    castleLedgeRight = pyglet.resource.image("Tiles/castleLedgeRight.png")
    castleLeft = pyglet.resource.image("Tiles/castleLeft.png")
    castleMid = pyglet.resource.image("Tiles/castleMid.png")
    castle = pyglet.resource.image("Tiles/castle.png")
    castleRight = pyglet.resource.image("Tiles/castleRight.png")
    dirtCenter = pyglet.resource.image("Tiles/dirtCenter.png")
    dirtCenter_rounded = pyglet.resource.image("Tiles/dirtCenter_rounded.png")
    dirtCliffLeftAlt = pyglet.resource.image("Tiles/dirtCliffLeftAlt.png")
    dirtCliffLeft = pyglet.resource.image("Tiles/dirtCliffLeft.png")
    dirtCliffRightAlt = pyglet.resource.image("Tiles/dirtCliffRightAlt.png")
    dirtCliffRight = pyglet.resource.image("Tiles/dirtCliffRight.png")
    dirtHalfLeft = pyglet.resource.image("Tiles/dirtHalfLeft.png")
    dirtHalfMid = pyglet.resource.image("Tiles/dirtHalfMid.png")
    dirtHalf = pyglet.resource.image("Tiles/dirtHalf.png")
    dirtHalfRight = pyglet.resource.image("Tiles/dirtHalfRight.png")
    dirtHillLeft2 = pyglet.resource.image("Tiles/dirtHillLeft2.png")
    dirtHillLeft = pyglet.resource.image("Tiles/dirtHillLeft.png")
    dirtHillRight2 = pyglet.resource.image("Tiles/dirtHillRight2.png")
    dirtHillRight = pyglet.resource.image("Tiles/dirtHillRight.png")
    dirtLedgeLeft = pyglet.resource.image("Tiles/dirtLedgeLeft.png")
    dirtLedgeRight = pyglet.resource.image("Tiles/dirtLedgeRight.png")
    dirtLeft = pyglet.resource.image("Tiles/dirtLeft.png")
    dirtMid = pyglet.resource.image("Tiles/dirtMid.png")
    dirt = pyglet.resource.image("Tiles/dirt.png")
    dirtRight = pyglet.resource.image("Tiles/dirtRight.png")
    door_closedMid = pyglet.resource.image("Tiles/door_closedMid.png")
    door_closedTop = pyglet.resource.image("Tiles/door_closedTop.png")
    door_openMid = pyglet.resource.image("Tiles/door_openMid.png")
    door_openTop = pyglet.resource.image("Tiles/door_openTop.png")
    fenceBroken = pyglet.resource.image("Tiles/fenceBroken.png")
    fence = pyglet.resource.image("Tiles/fence.png")
    grassCenter = pyglet.resource.image("Tiles/grassCenter.png")
    grassCenter_rounded = pyglet.resource.image("Tiles/grassCenter_rounded.png")
    grassCliffLeftAlt = pyglet.resource.image("Tiles/grassCliffLeftAlt.png")
    grassCliffLeft = pyglet.resource.image("Tiles/grassCliffLeft.png")
    grassCliffRightAlt = pyglet.resource.image("Tiles/grassCliffRightAlt.png")
    grassCliffRight = pyglet.resource.image("Tiles/grassCliffRight.png")
    grassHalfLeft = pyglet.resource.image("Tiles/grassHalfLeft.png")
    grassHalfMid = pyglet.resource.image("Tiles/grassHalfMid.png")
    grassHalf = pyglet.resource.image("Tiles/grassHalf.png")
    grassHalfRight = pyglet.resource.image("Tiles/grassHalfRight.png")
    grassHillLeft2 = pyglet.resource.image("Tiles/grassHillLeft2.png")
    grassHillLeft = pyglet.resource.image("Tiles/grassHillLeft.png")
    grassHillRight2 = pyglet.resource.image("Tiles/grassHillRight2.png")
    grassHillRight = pyglet.resource.image("Tiles/grassHillRight.png")
    grassLedgeLeft = pyglet.resource.image("Tiles/grassLedgeLeft.png")
    grassLedgeRight = pyglet.resource.image("Tiles/grassLedgeRight.png")
    grassLeft = pyglet.resource.image("Tiles/grassLeft.png")
    grassMid = pyglet.resource.image("Tiles/grassMid.png")
    grass = pyglet.resource.image("Tiles/grass.png")
    grassRight = pyglet.resource.image("Tiles/grassRight.png")
    hill_largeAlt = pyglet.resource.image("Tiles/hill_largeAlt.png")
    hill_large = pyglet.resource.image("Tiles/hill_large.png")
    hill_smallAlt = pyglet.resource.image("Tiles/hill_smallAlt.png")
    hill_small = pyglet.resource.image("Tiles/hill_small.png")
    ladder_mid = pyglet.resource.image("Tiles/ladder_mid.png")
    ladder_top = pyglet.resource.image("Tiles/ladder_top.png")
    liquidLava = pyglet.resource.image("Tiles/liquidLava.png")
    liquidLavaTop_mid = pyglet.resource.image("Tiles/liquidLavaTop_mid.png")
    liquidLavaTop = pyglet.resource.image("Tiles/liquidLavaTop.png")
    liquidWater = pyglet.resource.image("Tiles/liquidWater.png")
    liquidWaterTop_mid = pyglet.resource.image("Tiles/liquidWaterTop_mid.png")
    liquidWaterTop = pyglet.resource.image("Tiles/liquidWaterTop.png")
    lock_blue = pyglet.resource.image("Tiles/lock_blue.png")
    lock_green = pyglet.resource.image("Tiles/lock_green.png")
    lock_red = pyglet.resource.image("Tiles/lock_red.png")
    lock_yellow = pyglet.resource.image("Tiles/lock_yellow.png")
    rockHillLeft = pyglet.resource.image("Tiles/rockHillLeft.png")
    rockHillRight = pyglet.resource.image("Tiles/rockHillRight.png")
    ropeAttached = pyglet.resource.image("Tiles/ropeAttached.png")
    ropeHorizontal = pyglet.resource.image("Tiles/ropeHorizontal.png")
    ropeVertical = pyglet.resource.image("Tiles/ropeVertical.png")
    sandCenter = pyglet.resource.image("Tiles/sandCenter.png")
    sandCenter_rounded = pyglet.resource.image("Tiles/sandCenter_rounded.png")
    sandCliffLeftAlt = pyglet.resource.image("Tiles/sandCliffLeftAlt.png")
    sandCliffLeft = pyglet.resource.image("Tiles/sandCliffLeft.png")
    sandCliffRightAlt = pyglet.resource.image("Tiles/sandCliffRightAlt.png")
    sandCliffRight = pyglet.resource.image("Tiles/sandCliffRight.png")
    sandHalfLeft = pyglet.resource.image("Tiles/sandHalfLeft.png")
    sandHalfMid = pyglet.resource.image("Tiles/sandHalfMid.png")
    sandHalf = pyglet.resource.image("Tiles/sandHalf.png")
    sandHalfRight = pyglet.resource.image("Tiles/sandHalfRight.png")
    sandHillLeft2 = pyglet.resource.image("Tiles/sandHillLeft2.png")
    sandHillLeft = pyglet.resource.image("Tiles/sandHillLeft.png")
    sandHillRight2 = pyglet.resource.image("Tiles/sandHillRight2.png")
    sandHillRight = pyglet.resource.image("Tiles/sandHillRight.png")
    sandLedgeLeft = pyglet.resource.image("Tiles/sandLedgeLeft.png")
    sandLedgeRight = pyglet.resource.image("Tiles/sandLedgeRight.png")
    sandLeft = pyglet.resource.image("Tiles/sandLeft.png")
    sandMid = pyglet.resource.image("Tiles/sandMid.png")
    sand = pyglet.resource.image("Tiles/sand.png")
    sandRight = pyglet.resource.image("Tiles/sandRight.png")
    signExit = pyglet.resource.image("Tiles/signExit.png")
    signLeft = pyglet.resource.image("Tiles/signLeft.png")
    sign = pyglet.resource.image("Tiles/sign.png")
    signRight = pyglet.resource.image("Tiles/signRight.png")
    snowCenter = pyglet.resource.image("Tiles/snowCenter.png")
    snowCenter_rounded = pyglet.resource.image("Tiles/snowCenter_rounded.png")
    snowCliffLeftAlt = pyglet.resource.image("Tiles/snowCliffLeftAlt.png")
    snowCliffLeft = pyglet.resource.image("Tiles/snowCliffLeft.png")
    snowCliffRightAlt = pyglet.resource.image("Tiles/snowCliffRightAlt.png")
    snowCliffRight = pyglet.resource.image("Tiles/snowCliffRight.png")
    snowHalfLeft = pyglet.resource.image("Tiles/snowHalfLeft.png")
    snowHalfMid = pyglet.resource.image("Tiles/snowHalfMid.png")
    snowHalf = pyglet.resource.image("Tiles/snowHalf.png")
    snowHalfRight = pyglet.resource.image("Tiles/snowHalfRight.png")
    snowHillLeft2 = pyglet.resource.image("Tiles/snowHillLeft2.png")
    snowHillLeft = pyglet.resource.image("Tiles/snowHillLeft.png")
    snowHillRight2 = pyglet.resource.image("Tiles/snowHillRight2.png")
    snowHillRight = pyglet.resource.image("Tiles/snowHillRight.png")
    snowLedgeLeft = pyglet.resource.image("Tiles/snowLedgeLeft.png")
    snowLedgeRight = pyglet.resource.image("Tiles/snowLedgeRight.png")
    snowLeft = pyglet.resource.image("Tiles/snowLeft.png")
    snowMid = pyglet.resource.image("Tiles/snowMid.png")
    snow = pyglet.resource.image("Tiles/snow.png")
    snowRight = pyglet.resource.image("Tiles/snowRight.png")
    stoneCenter = pyglet.resource.image("Tiles/stoneCenter.png")
    stoneCenter_rounded = pyglet.resource.image("Tiles/stoneCenter_rounded.png")
    stoneCliffLeftAlt = pyglet.resource.image("Tiles/stoneCliffLeftAlt.png")
    stoneCliffLeft = pyglet.resource.image("Tiles/stoneCliffLeft.png")
    stoneCliffRightAlt = pyglet.resource.image("Tiles/stoneCliffRightAlt.png")
    stoneCliffRight = pyglet.resource.image("Tiles/stoneCliffRight.png")
    stoneHalfLeft = pyglet.resource.image("Tiles/stoneHalfLeft.png")
    stoneHalfMid = pyglet.resource.image("Tiles/stoneHalfMid.png")
    stoneHalf = pyglet.resource.image("Tiles/stoneHalf.png")
    stoneHalfRight = pyglet.resource.image("Tiles/stoneHalfRight.png")
    stoneHillLeft2 = pyglet.resource.image("Tiles/stoneHillLeft2.png")
    stoneHillRight2 = pyglet.resource.image("Tiles/stoneHillRight2.png")
    stoneLedgeLeft = pyglet.resource.image("Tiles/stoneLedgeLeft.png")
    stoneLedgeRight = pyglet.resource.image("Tiles/stoneLedgeRight.png")
    stoneLeft = pyglet.resource.image("Tiles/stoneLeft.png")
    stoneMid = pyglet.resource.image("Tiles/stoneMid.png")
    stone = pyglet.resource.image("Tiles/stone.png")
    stoneRight = pyglet.resource.image("Tiles/stoneRight.png")
    stoneWall = pyglet.resource.image("Tiles/stoneWall.png")
    tiles_spritesheet = pyglet.resource.image("Tiles/tiles_spritesheet.png")
    tochLit2 = pyglet.resource.image("Tiles/tochLit2.png")
    tochLit = pyglet.resource.image("Tiles/tochLit.png")
    torch = pyglet.resource.image("Tiles/torch.png")
    window = pyglet.resource.image("Tiles/window.png")
